world = ['Италия', 'Франция', 'Испания', 'Америка', 'Австрия']
print(world)
print(sorted(world))
print(world)
print(sorted(world, reverse = True))
print(world)
world.reverse()
print(world)
world.reverse()
print(world)
world.sort()
print(world)
world.sort(reverse = True)
print(world)